services:
  zed:
    build: .
    restart: on-failure
    command: /code/run.sh
    container_name: zed
    hostname: zed
    volumes:
      - db:/app/db.sqlite3
    ports:
      - "8000:8000"
volumes:
  db:
