# Generated by Django 5.0.3 on 2024-03-17 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedComment',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('like_count', models.IntegerField(default=0, verbose_name='comment like count')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.comment', verbose_name='liked comment')),
                ('liker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='comment liker')),
            ],
            options={
                'verbose_name': 'LikedComment',
                'verbose_name_plural': 'LikedComments',
                'db_table': 'LikedComment',
            },
        ),
        migrations.CreateModel(
            name='LikedPost',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('like_count', models.IntegerField(default=0, verbose_name='post like count')),
                ('liker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='post liker')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.post', verbose_name='liked post')),
            ],
            options={
                'verbose_name': 'LikedPost',
                'verbose_name_plural': 'LikedPosts',
                'db_table': 'LikedPost',
            },
        ),
        migrations.CreateModel(
            name='LikeNotification',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notified', to=settings.AUTH_USER_MODEL, verbose_name='notified user')),
                ('notifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to=settings.AUTH_USER_MODEL, verbose_name='notifier user')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.post')),
            ],
            options={
                'verbose_name': 'LikeNotification',
                'verbose_name_plural': 'LikeNotifications',
                'db_table': 'LikeNotification',
            },
        ),
    ]
