# Generated by Django 5.0.3 on 2024-03-17 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_repost_created_time_repost_modified_time_and_more'),
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedcomment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_comments', to='content.comment', verbose_name='liked comment'),
        ),
        migrations.AlterField(
            model_name='likedcomment',
            name='liker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_comments', to=settings.AUTH_USER_MODEL, verbose_name='comment liker'),
        ),
        migrations.AlterField(
            model_name='likedpost',
            name='liker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='post liker'),
        ),
        migrations.AlterField(
            model_name='likedpost',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='content.post', verbose_name='liked post'),
        ),
        migrations.AlterField(
            model_name='likenotification',
            name='notified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL, verbose_name='notified user'),
        ),
        migrations.AlterField(
            model_name='likenotification',
            name='notifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='notifier user'),
        ),
        migrations.AlterField(
            model_name='likenotification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_notifications', to='content.post'),
        ),
    ]
