# Generated by Django 5.0.3 on 2024-03-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_alter_likedcomment_comment_alter_likedcomment_liker_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='likedcomment',
            table='liked_comment',
        ),
        migrations.AlterModelTable(
            name='likedpost',
            table='liked_post',
        ),
        migrations.AlterModelTable(
            name='likenotification',
            table='like_notification',
        ),
    ]
