# Generated by Django 5.0.3 on 2024-03-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='relation',
            table='relation',
        ),
    ]
