# Generated by Django 5.0.3 on 2024-03-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_comment_table_alter_post_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='content.topic', verbose_name='post topic'),
        ),
    ]
