# Generated by Django 5.0.3 on 2024-03-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_post_topic_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='posts', to='content.topic', verbose_name='post topic'),
        ),
    ]
